FROM python:latest

WORKDIR /django_app

#prevent Python from writing.pyc files
ENV PYTHONDONTWRITEBYTECODE 1
#ensure Python output is sent directly to the terminal without buffering
ENV PYTHONUNBUFFERED 1
#prevent terminal from asking user for input
ENV DEBIAN_FRONTEND=noninteractive

RUN pip install --upgrade pip
COPY ./requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY ./entrypoint.sh entrypoint.sh 
RUN chmod +x ./entrypoint.sh

COPY . .

ENTRYPOINT ["./entrypoint.sh"]




